### ISSUE TITLE
Fieldmanager_Grid deprecated jQuery and unable to save

### ISSUE THREAD

**Issue by jjrdevspace01** [alleyinteractive/fieldmanager-demos#19]
tried to use Fieldmanager_Grid for the first time, i've had no problems with the other fieldmanager classes
followed the demo here https://github.com/alleyinteractive/fieldmanager-demos/blob/master/lib/class-fm-demo-grid.php
```
            'table' => new Fieldmanager_Grid( array(
                'js_options' => array(
                    'startRows'    => 6,
                    'startCols'    => 5,
                    'colHeaders'   => true,
                    'rowHeaders'   => true,
                    'minSpareCols' => 1,
                    'minSpareRows' => 1,
                    'contextMenu'  => true,
                )
            )),

```
First problem was 'grid.js?ver=1.2.6:88 Uncaught TypeError: $(...).live is not a function

managed to work around that installing the plugin 'enable-jquery-migrate-helper'

However although this allowed the grid to display correctly i was unable to use the control to save data to the post_meta

**Comment by dlh01** [comment]
Thanks for the report, @jjrdevspace01. Could you please file it at the Fieldmanager repo along with the code for the field? We will need to decide what to do there about the use of removed jQuery functions. https://github.com/alleyinteractive/wordpress-fieldmanager/issues
