### ISSUE TITLE
Use same $fm object for multiple groups?

### ISSUE THREAD

**Issue by jjeaton** [alleyinteractive/fieldmanager-demos#6]
I've noticed most of the demos reuse the same `$fm` variable to instantiate each separate fieldmanager group. [Example here, each group uses `$fm`](https://github.com/alleyinteractive/fieldmanager-demos/blob/master/lib/class-fm-demo-context-term.php#L30). Is it safe to do it this way in production code, or should each group have a differently-named variable. It seems to work fine either way.

**Comment by mboynes** [comment]
Yes, it's perfectly safe to use the same variable this way. It doesn't matter either way, so developer's preference.
